# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import edc_base.model.fields.uuid_auto_field
import edc_base.model.validators.date
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0003_arv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='kmotingwa', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('report_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text="If reporting today, use today's date/time, otherwise use the date/time this information was reported.", validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model.validators.date.datetime_not_future], verbose_name='Report Date')),
                ('consent_version', models.CharField(default='?', editable=False, max_length=10)),
                ('first_documentation_of_Pregnancy_date', models.DateField()),
                ('delivery_date', models.DateField()),
            ],
            options={
                'verbose_name': 'ARV',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='pregnancyhistory',
            name='pregnancy_details',
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ba_namotswe.PregnancyHistory'),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='subject_visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ba_namotswe.SubjectVisit'),
        ),
    ]
