# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import edc_base.model.fields.uuid_auto_field
import edc_base.model.validators.date
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0004_auto_20161025_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='kmotingwa', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('report_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text="If reporting today, use today's date/time, otherwise use the date/time this information was reported.", validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model.validators.date.datetime_not_future], verbose_name='Report Date')),
                ('consent_version', models.CharField(default='?', editable=False, max_length=10)),
                ('transfer_date', models.DateField()),
                ('transfer_reason', models.CharField(max_length=100)),
                ('subject_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ba_namotswe.SubjectVisit')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ba_namotswe.TransferHistory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pregnancy',
            options={},
        ),
        migrations.AlterField(
            model_name='arv',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
