# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0005_auto_20161025_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraction',
            old_name='io_history',
            new_name='oi_history',
        ),
        migrations.AddField(
            model_name='pregnancyhistory',
            name='pregnancy_details',
            field=models.CharField(choices=[('date_of_first_clinical_documentation_of_pregnancy', 'Date of First Clinical Documentation of Pregnancy'), ('date_of_delivery', 'Date of Delivery')], max_length=7, null=True, verbose_name='Has the participant moved out of the household where last seen'),
        ),
    ]
